name: Update data.json

#on:
 # push:
  #  branches: [ main ]
  #pull_request:
   # branches: [ main ]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:

    - name: Update data.json values
      uses: restackio/update-json-values-action@v1.0.0
      with:
        file: data.json
        values: "{\"prismicRef\": \"${{ github.token }}\"}"
